# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22944194d11d67a65248c1497757a4070e1d578139494ea5394f6757c14b047a833f7684fdf2091df7f4d0deb59608125003363d529b1356124018c81ca4e57c

test:
  secret_key_base: 961560d4fcbc1b7156a0fc4f927dfb6ca70bd643744fb9556868d1732550d3328d9d57034ffec9dbd054df22c75f0eb7bb850f866d1af9c10207ffc68dfd8159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
